version: '3.8'

services:
  # Base de Datos
  db:
    image: postgres:15-alpine
    container_name: challenge_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: challenge_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db

  # Futuro servicio de Frontend (opcional a futuro)
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"

volumes:
  postgres_data: